### PR TITLE
course planning: permit users to schedule faculty for completely new courses

### PR DESCRIPTION
**Pull request by jxjj**
ScreenShot 2024-02-07 at 16 42 09

This permits users in course planning mode to tentatively schedule faculty for never-been taught courses (i.e. courses that don't exist yet in the SIS). Some tests are added for the course planning api.

## On Testing

The goal of this feature branch is to let users create courses that don't exist yet in the SIS. In my first experiments, things would break – but it would be difficult to discover when and where until later because currently there are no tests for the course planning section.

I've been avoiding tests in for course planning stuff because:
- the course planning section depends on data from Bandaid, a 3rd party API. 
- to add tests, we'll need to mock Bandaid's API responses. 
- since Bandaid does it's API call via Laravel, cypress testing won't intercept... which requires writing tests for php.

This PR adds feature tests for the API using Pest. The Guzzle Http client is swapped for Laravel's `Http` class, so that we can do `Http::fake()` to intercept 3rd party api requests.

The Bandaid tests aren't comprehensive – just enough to catch issues with local/sis courses and sections.

## Approach

With testing in place, I simplified my approach. 

Originally, I tried  to create a `Course` model with a robust relationships to `CourseSection` and logic to handle cases where sections and courses may or may not exist locally. Then I briefly considered pulling down all sis data locally.  In the end, I let `courses` exist with only a relationship to a `group`, and let the front end handle the relationships between courses and sections (since it did this anyway for sis data).

## UI

On the front-end, when a user creates a new course - they can add a new option if they can't find it in the list. This option is purposely tucked away at the bottom. It should rarely be needed, and putting it more prominently at the top might lead users to create new courses rather than using existing ones.

ScreenShot 2024-02-07 at 16 40 05@2x

### CODE REVIEW

**Review by cmcfadden — COMMENTED** [review]
Could we consider visually distinguishing existing courses from new courses in planning mode? If folks are doing speculative planning, it'd be helpful for them to see which courses are actually on the books and which ones might not be.

**Review by cmcfadden — COMMENTED** [review]
I'm not sure if it's something in this PR, but filtering in planning mode seems broken right now? I don't see anything obvious looking at the PR

**Comment by jxjj** [comment]
**Re: Filtering.** What are you seeing? I didn't notice anything as I very methodically clicked at totally random.
ScreenShot 2024-02-16 at 10 18 42

**New Course signifier** Like this idea. Suggestions? Special emoji like ✨? Append text like "(Draft)" or something?

Related. I've been inconsistent to how I've been distinguishing planning mode content: what's "real" and what's "tentative"
- `isPublished: boolean`
- `source: 'sis' | 'local'`
- something else?

**Comment by cmcfadden** [comment]
Here's what I'm seeing - for example, toggling IND off doesn't make the IND courses go away? (Anthropology, dev server)

https://github.com/UMN-LATIS/bluesheet/assets/211655/b60cea09-94f6-4cdc-9b21-05640cf3f8e7


I think the source flag makes the most sense, as it gives us flexibility going forward.

For the local courses, maybe a color hue + a dotted/dashed border (separate from the existing hover control)?

**Review by cmcfadden — APPROVED** [review]

**Pull request merged**
