### PR TITLE
fix roles not listing in Combobox

### PR DESCRIPTION
**Pull request by jxjj**
Resolves:
- #39 

Also fixes an issue where a user adding a new role to one member, wouldn't see that new role as an option in the roles dropdown for other members.

ScreenShot 2023-08-22 at 12 08 56@2x

### CODE REVIEW

**Comment by cmcfadden** [comment]
Something still doesn't seem to be working? Testing on dev:


https://github.com/UMN-LATIS/bluesheet/assets/211655/1c3ce3c4-f69a-4431-baaa-b5da86295381

**Comment by jxjj** [comment]
> Something still doesn't seem to be working? Testing on dev:
> 
>  Screen.Recording.2023-08-22.at.12.56.47.PM.mov

Yep – This is a separate issue (#38 ), so I'll do a separate PR.

**Comment by jxjj** [comment]
Or not! apparently I forgot to switch branches. 🤣

**Comment by jxjj** [comment]
This PR now fixes #38.

Issue was related to using an `index` as key on a `v-for`. Switching to `member.id`, resolved things.

Also fixed: When a user clicks the remove member button, the membership end_date will now be properly updated. (It was mutating local state, but not emitting the `update:members` event with the updated members.

**Review by cmcfadden — APPROVED** [review]

**Pull request merged**
