### PR TITLE
Improve drag and drop performance on course sections table

### PR DESCRIPTION
**Pull request by jxjj**
This replaces the VueDraggable with a simpler drag and drop component

<table>
<tr>
<th>Before</th>
<th>After</th>
<tr>
<td>

</td>
<td>

</td>
</tr>
</table>

## Details

In the image above, you can see the lag as I drag a single item around the page for the Anthropology dept.

For larger departments (e.g. Anthro), drag and drop with VueDraggable became unusable.  Every `dragover` event triggered a number of function calls (`dragOverCompleted` and `getBoundingClientRect`) proportional to the number of drop zones and items on the page on the page. And since dragover fires every few hundred milliseconds, the app would slow to a crawl when there were a large number of faculty and sections.

Reducing the number of uses of the Draggable component showed modest – but not great – improvements. Drastically simplifying the DOM of the dragged item (to just the course id) helped  too – maybe because drag events are fired by children in the drop zone in addition to parents. 

Still, we don't need much functionality in VueDraggable, so this PR replaces it with our own MUCH simpler `<DragDrop>` component, with a similar API as VueDraggable.

Further performance gains could be made if desired, by changing to optimistic updates of the stores. Currently, we're waiting for the API call to complete before updating the sections/enrollments. Instead, we could update the store and rollback if the update fails.

On dev for testing: https://cla-groups-dev.oit.umn.edu/course-planning/groups/6

### CODE REVIEW

**Comment by jxjj** [comment]
super. something crazy happening in safari... of course

**Comment by cmcfadden** [comment]
Is it blocking your crypto miner? I've told you to stop trying to sneak those in.

**Comment by jxjj** [comment]
ok fixed, I think.

Weirdly, safari didn't seem like the CSS transform on the menu chevrons in the table during the drag and drop events. Removed those and just added a separate right chevron instead of rotating the down one.

**Comment by cmcfadden** [comment]
Performance is way better, but I'm seeing some sorta glitch, maybe one when moving courses to adjacent cells?


https://github.com/UMN-LATIS/bluesheet/assets/211655/1e0b4567-3b8a-417f-a5b6-2f69638bd844

**Comment by jxjj** [comment]
Good catch on the glitch.

It was a race condition between the drag drop target and source lists. 

Normally:
1.  the `dragleave` event would fire when leaving the previous dragdrop zone, setting the target zone to `null`
2. then the `dragenter`  would fire when entering the next dragdrop zeon, setting the target zone to the new one

However, in some cases the `dragleave` event would fire AFTER the `dragenter`, nulling out the newly entered drag zone. It was worse in Safari, but could be triggered in Chrome too.

The fix is to only allow a drag drop component to set target to null, if it's the target.

Other tweaks:
- Removed old enrollment before doing any section/enrollment updates. Previously, it would look like the section was briefly bouncing to another instructor to the UI.
- removed optimistic updates to simplify troubleshooting the race condition glitch above, and to avoid an issue where a user might make multiple moves before the api calls complete. 
- Added simple CSS fade transition to make ui updates less jarring.

Updates pushed to dev: https://cla-groups-dev.oit.umn.edu/course-planning/groups/6

**Comment by cmcfadden** [comment]
this looks good!

**Pull request merged**
